#!/bin/sh
# Bakes the installed demo state: runs the install of the php-fpm image once against throw-away
# MySQL and OpenSearch containers and exports what a fresh pod otherwise generates on every start:
#   <out>/mysql/initdb/demo.sql.gz   database dump, loaded by the mysql image on its first start
#   <out>/php/state/                 files generated by the install (thumbnails, var/config, ...)
# Used by .github/workflows/build.yml (job "bake") and for local checks.
#
# Usage: PHP_IMAGE=ghcr.io/coreshop/demo-enterprise/php-fpm:<tag> .docker/bake/bake.sh [<out>]
# Required env: PIMCORE_ENCRYPTION_SECRET, PIMCORE_INSTANCE_IDENTIFIER, PIMCORE_PRODUCT_KEY
#   (the same values the deployment uses; the encryption secret must match the runtime one)
# Optional env: MYSQL_DATABASE (app), MYSQL_USER (pimcore), MYSQL_PASSWORD (pimcore),
#   ADMIN_USERNAME (admin), ADMIN_PASSWORD (coreshop), DOCKER_PLATFORM (e.g. linux/amd64)
set -eu

OUT=${1:-bake}
PHP_IMAGE=${PHP_IMAGE:?PHP_IMAGE is required}
MYSQL_IMAGE=${MYSQL_IMAGE:-mysql:8}
OPENSEARCH_IMAGE=${OPENSEARCH_IMAGE:-opensearchproject/opensearch:2.11.1}
MYSQL_DATABASE=${MYSQL_DATABASE:-app}
MYSQL_USER=${MYSQL_USER:-pimcore}
MYSQL_PASSWORD=${MYSQL_PASSWORD:-pimcore}
ADMIN_USERNAME=${ADMIN_USERNAME:-admin}
ADMIN_PASSWORD=${ADMIN_PASSWORD:-coreshop}
PLATFORM_ARG=${DOCKER_PLATFORM:+--platform $DOCKER_PLATFORM}
NAME=bake-$$

for var in PIMCORE_ENCRYPTION_SECRET PIMCORE_INSTANCE_IDENTIFIER PIMCORE_PRODUCT_KEY; do
  if [ -z "$(printenv "$var")" ]; then echo "$var is not set" >&2; exit 1; fi
done

cleanup() {
  docker rm -f "$NAME-php" "$NAME-mysql" "$NAME-opensearch" >/dev/null 2>&1 || true
  docker network rm "$NAME" >/dev/null 2>&1 || true
}
trap cleanup EXIT

docker network create "$NAME" >/dev/null
docker run -d --name "$NAME-mysql" --network "$NAME" \
  -e MYSQL_ROOT_PASSWORD="$MYSQL_PASSWORD" -e MYSQL_DATABASE="$MYSQL_DATABASE" \
  -e MYSQL_USER="$MYSQL_USER" -e MYSQL_PASSWORD="$MYSQL_PASSWORD" \
  "$MYSQL_IMAGE" --skip-log-bin >/dev/null
docker run -d --name "$NAME-opensearch" --network "$NAME" \
  -e discovery.type=single-node -e plugins.security.disabled=true \
  -e OPENSEARCH_JAVA_OPTS='-Xms512m -Xmx512m' -e action.auto_create_index=false \
  "$OPENSEARCH_IMAGE" >/dev/null

echo "Running the install in $PHP_IMAGE"
start=$(date +%s)
# shellcheck disable=SC2086
docker run --name "$NAME-php" --network "$NAME" $PLATFORM_ARG \
  -e APP_ENV=prod -e APP_DEBUG=0 \
  -e DATABASE_USER="$MYSQL_USER" -e DATABASE_PASSWORD="$MYSQL_PASSWORD" -e DATABASE_NAME="$MYSQL_DATABASE" \
  -e DATABASE_HOST="$NAME-mysql" -e DATABASE_PORT=3306 -e DATABASE_VERSION=8.0 \
  -e DATABASE_URL="mysql://$MYSQL_USER:$MYSQL_PASSWORD@$NAME-mysql:3306/$MYSQL_DATABASE?serverVersion=8.0&charset=utf8mb4" \
  -e PIMCORE_OPENSEARCH_DSN="opensearch://$NAME-opensearch:9200?ssl=false" \
  -e PIMCORE_MESSENGER_TRANSPORT_DSN_PREFIX="doctrine://default?queue_name=" \
  -e PIMCORE_ENCRYPTION_SECRET -e PIMCORE_INSTANCE_IDENTIFIER -e PIMCORE_PRODUCT_KEY \
  -e PIMCORE_INSTALL_ADMIN_USERNAME="$ADMIN_USERNAME" -e PIMCORE_INSTALL_ADMIN_PASSWORD="$ADMIN_PASSWORD" \
  --entrypoint sh "$PHP_IMAGE" -c 'until curl -sf -o /dev/null "http://'"$NAME"'-opensearch:9200"; do echo "Waiting for OpenSearch..."; sleep 2; done; /usr/local/bin/wait_db && /usr/local/bin/install'
echo "Install finished in $(( $(date +%s) - start )) s"

rm -rf "$OUT"
mkdir -p "$OUT/mysql/initdb" "$OUT/php/state/public/var" "$OUT/php/state/var"
cp .docker/mysql/Dockerfile "$OUT/mysql/Dockerfile"
cp .docker/php/Dockerfile.installed "$OUT/php/Dockerfile"

echo "Dumping the database"
docker exec "$NAME-mysql" sh -c 'mysqldump -uroot -p"$MYSQL_ROOT_PASSWORD" --single-transaction --routines --triggers --no-tablespaces "$MYSQL_DATABASE"' 2>/dev/null \
  | gzip -6 > "$OUT/mysql/initdb/demo.sql.gz"

echo "Exporting the generated files"
# thumbnails and other generated public files
docker cp "$NAME-php:/var/www/html/public/var/tmp" "$OUT/php/state/public/var/tmp"
# configuration written by the installer and the bundle installers
docker cp "$NAME-php:/var/www/html/var/config" "$OUT/php/state/var/config"
rm -f "$OUT/php/state/var/config/needs-install.lock"

du -sh "$OUT/mysql/initdb/demo.sql.gz" "$OUT/php/state/public/var/tmp" "$OUT/php/state/var/config"
