pimcore:
    assets:
        image:
            thumbnails:
                definitions:
                    coreshop_productInvoice:
                        items:
                            -
                                method: scaleByWidth
                                arguments:
                                    width: 100
                        medias: {  }
                        name: coreshop_productInvoice
                        description: ''
                        group: CoreShop
                        format: SOURCE
                        quality: 90
                        highResolution: 0.0
                        preserveColor: false
                        preserveMetaData: false
                        rasterizeSVG: false
                        downloadable: false
                        modificationDate: 1702546726
                        creationDate: 1702546726
                        preserveAnimation: false
