imports:
    - { resource: services.yaml }
    - { resource: 'local/' }

lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%' # required for token creation
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%' # required for token verification
    pass_phrase: '%env(JWT_PASSPHRASE)%' # required for token creation
    token_ttl: 3600 # in seconds, default is 3600

core_shop_store:
    resources:
        store:
            classes:
                model: App\Entity\Store

doctrine:
    orm:
        mappings:
            app:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
    dbal:
        connections:
            default:
                user: '%env(DATABASE_USER)%'
                password: '%env(DATABASE_PASSWORD)%'
                dbname: '%env(DATABASE_NAME)%'
                host: '%env(DATABASE_HOST)%'
                port: '%env(DATABASE_PORT)%'
                server_version: '%env(DATABASE_VERSION)%'

core_shop_customer_cluster:
    pimcore_admin:
        js:
            store_extension: '/bundles/coreshopcustomercluster/pimcore/static/js/store/item.js'
