parameters:
    secret: '%env(APP_SECRET)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $batchTaskRepository: '@coreshop_batch_messenger.repository.task'
            $batchZipStorage: '@coreshop_batch_messenger.zip.storage'

    App\Controller\:
        resource: '../src/Controller'
        public: true
        tags: [ 'controller.service_arguments' ]

    App\Command\:
        resource: '../src/Command/*'
        tags: [ 'console.command' ]

    App\EventListener\:
        resource: '../src/EventListener/'

    Twig\DeferredExtension\DeferredExtension: ~