pimcore_static_routes:
    definitions:
        coreshop_loyalty_loyalty:
            name: coreshop_loyalty_loyalty
            pattern: '/(\w+)\/shop\/loyalty/'
            reverse: /%%_locale/shop/loyalty
            controller: 'CoreShop\Bundle\LoyaltyBundle\Controller\LoyaltyVouchersController::loyaltyAction'
            variables: '_locale'
            defaults: null
            siteId: {  }
            methods:
                - GET
            priority: 3
            creationDate: 1702156707
            modificationDate: 1702156707
        coreshop_loyalty_vouchers_redeem:
            name: coreshop_loyalty_vouchers_redeem
            pattern: '/(\w+)\/shop\/loyalty\/(.*)/'
            reverse: /%%_locale/shop/loyalty/%%voucher
            controller: 'CoreShop\Bundle\LoyaltyBundle\Controller\LoyaltyVouchersController::redeemAction'
            variables: '_locale,voucher'
            defaults: null
            siteId: {  }
            methods:
                - POST
            priority: 3
            creationDate: 1702156707
            modificationDate: 1702156707
