pimcore_static_routes:
  definitions:
    coreshop_voucher_credit:
      name: coreshop_voucher_credit
      pattern: /(\w+)\/shop\/vouchers/
      reverse: /%_locale/shop/vouchers
      controller: 'CoreShop\Bundle\VoucherCreditBundle\Controller\VouchersController::listAction'
      variables: _locale
      defaults: null
      siteId: {  }
      methods: {  }
      priority: 3

    coreshop_partial_cart_voucher_add:
      name: coreshop_partial_cart_voucher_add
      pattern: '/_partial\/cart\/add\-voucher$/'
      reverse: /_partial/cart/add-voucher
      controller: 'CoreShop\Bundle\VoucherCreditBundle\Controller\VoucherCartController::addVoucherAction'
      variables: ''
      defaults: null
      siteId: {  }
      methods: {  }
      priority: 3

    coreshop_cart_add_voucher:
      name: coreshop_cart_add_voucher
      pattern: '/(\w+)\/shop\/cart\/add\-voucher$/'
      reverse: /%%_locale/shop/cart/add-voucher
      controller: 'CoreShop\Bundle\VoucherCreditBundle\Controller\VoucherCartController::addVoucherAction'
      variables: '_locale'
      defaults: null
      siteId: {  }
      methods:
        - POST
      priority: 3
