pimcore_static_routes:
    definitions:
        coreshop_cart_list:
            name: coreshop_cart_list
            pattern: /(\w+)\/shop\/cart\/list/
            reverse: /%_locale/shop/cart/list
            controller: 'coreshop.storage_list.controller_multi_list.order::listStorageListAction'
            variables: _locale
            defaults: null
            siteId: {  }
            methods:
                - POST
                - GET
            priority: 3
            creationDate: 1733409940
            modificationDate: 1733409940
