pimcore_static_routes:
    definitions:
        coreshop_logout:
            name: coreshop_logout
            pattern: /(\w+)\/shop\/logout$/
            reverse: /%_locale/shop/logout
            controller: 'CoreShop\Bundle\FrontendBundle\Controller\SecurityController::logoutAction'
            variables: _locale
            defaults: null
            siteId: {  }
            methods: {  }
            priority: 2
            creationDate: 1702546722
            modificationDate: 1702546722
